### PR TITLE
#104 depandabot Added

### PR DESCRIPTION
**Pull request by k-deepak04**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of GSSOC23

### CODE REVIEW

**Comment by k-deepak04** [comment]
this closes #104

**Comment by k-deepak04** [comment]
@KOMALDEWNANI @Fenrir-04 please review and merge this
and add respective labels :)

**Comment by k-deepak04** [comment]
image


image

image

it will update the versions automatically that are outdated

**Comment by KOMALDEWNANI** [comment]
This would create a pull request when versions are outdated, right?

**Comment by KOMALDEWNANI** [comment]
Dependency updates might introduce breaking changes or require additional adjustments in our codebase. Therefore, it's recommended to have proper testing and review processes in place to ensure the updates integrate smoothly into our project.

**Comment by k-deepak04** [comment]
> This would create a pull request when versions are outdated, right?

maybe it will automatically commit without creating 
it's a guess don't know for sure

**Comment by k-deepak04** [comment]
> Dependency updates might introduce breaking changes or require additional adjustments in our codebase. Therefore, it's recommended to have proper testing and review processes in place to ensure the updates integrate smoothly into our project.

don't worry it do not do dependency updates
it just handles the dependency issues
for example i started working on a issue and added a pr but i used various version for doing the same thing and in our codebase the version is different so it will take care of such issues

**Comment by k-deepak04** [comment]
it won't update the versions on it's own it will just resolve the things 
hope you got what i'm trying to say

**Comment by KOMALDEWNANI** [comment]
> > Dependency updates might introduce breaking changes or require additional adjustments in our codebase. Therefore, it's recommended to have proper testing and review processes in place to ensure the updates integrate smoothly into our project.
> 
> don't worry it do not do dependency updates it just handles the dependency issues for example i started working on a issue and added a pr but i used various version for doing the same thing and in our codebase the version is different so it will take care of such issues

Could you please give a demo of it?

**Comment by k-deepak04** [comment]
how can i :(

> > > Dependency updates might introduce breaking changes or require additional adjustments in our codebase. Therefore, it's recommended to have proper testing and review processes in place to ensure the updates integrate smoothly into our project.
> > 
> > 
> > don't worry it do not do dependency updates it just handles the dependency issues for example i started working on a issue and added a pr but i used various version for doing the same thing and in our codebase the version is different so it will take care of such issues
> 
> Could you please give a demo of it?

how can i :(

**Comment by k-deepak04** [comment]
@KOMALDEWNANI i have integrated this in more than 4 projects and it didn't created any issue and working great
if you want to merge this you can or close the PR
anything is fine with with me :)

**Comment by KOMALDEWNANI** [comment]
> @KOMALDEWNANI i have integrated this in more than 4 projects and it didn't created any issue and working great if you want to merge this you can or close the PR anything is fine with with me :)

Yes, this is what I want. Show me how it works in any of your old projects.

**Comment by k-deepak04** [comment]
@KOMALDEWNANI Already added the screenshots of old projects

**Comment by k-deepak04** [comment]
Okay so i researched about it and it won't automaticlly add updates
It will create pr and then it's upto you that you want to add or not

**Comment by k-deepak04** [comment]
Keeping your dependencies updated is one of the easiest ways to keep the software you build secure. However, while it’s critically important to keep your dependencies updated, in a recent survey, 52% of developers said they find it painful1. Dependabot alleviates that pain by updating your dependencies automatically, so you can spend less time updating dependencies and more time building. Up until now, the Dependabot features we’ve brought to GitHub have focused on automated security updates, which update packages that have known vulnerabilities.
Your configuration file tells Dependabot the kind of dependency you want to update (like Go modules or npm packages), where the dependency manifest is located, and how often you want Dependabot to look for updates. On the schedule you specify, Dependabot will check if new versions are available. If updates are available, Dependabot sends pull requests to update your dependency manifest with the new versions.

**Comment by KOMALDEWNANI** [comment]
Got it. Thanks! 🚀

**Comment by k-deepak04** [comment]
@KOMALDEWNANI bro please remove these labels as i have added the bots in other repo also
so it will be counted in spam
Happy to contribute , will look for some other issues
just remove the labels thanks :)

**Pull request merged**
