### PR TITLE
Trending category added

### PR DESCRIPTION
**Pull request by kartikayasija**
## 📷 Screenshots

image

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of GSSOC23

### CODE REVIEW

**Comment by KOMALDEWNANI** [comment]
Have you implemented the functionality to display trending videos or just added a category?

**Comment by kartikayasija** [comment]
I have just added a category for now. Please tell me if I need to implement its functionality, I can do that.

**Comment by Fenrir-04** [comment]
@kartikayasija please add functionality as well to the trending category.

**Comment by kartikayasija** [comment]
@Fenrir-04 The trending functionality is implemented, but the API you have used is not fetching correct data, It only fetches the data of youtube search not the category. This is the problem with every Category.
 I think we should use official youtube API for this project.
Only these endpoints are available with this API
image

**Comment by KOMALDEWNANI** [comment]
Yes @kartikayasija please work on Issue #89 first and then implement trending category.

**Comment by kartikayasija** [comment]
Sure @KOMALDEWNANI

**Comment by Fenrir-04** [comment]
hey @kartikayasija you have some conflicts in constants.js file, please solve them asap

**Pull request closed without merging**
