### PR TITLE
#105 Old issue bot added

### PR DESCRIPTION
**Pull request by k-deepak04**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of GSSOC23

### CODE REVIEW

**Comment by k-deepak04** [comment]
image

greeting bot is also working
after filing this PR i received the greeting :)

**Comment by Fenrir-04** [comment]
@k-deepak04 yeah i also received the greeting :)

**Comment by k-deepak04** [comment]
@Fenrir-04 bro please add level tag also in the PR, so that it will count properly in the gssoc'23 :)

**Comment by k-deepak04** [comment]
@Fenrir-04 bro please remove these labels as i have added the bots in other repo also
so it will be counted in spam
Happy to contribute , will look for some other issues
just remove the labels thanks :)

**Comment by k-deepak04** [comment]
@Fenrir-04 please add labels tags in the PR :)

**Pull request merged**
