### PR TITLE
[FEATURE] Authentication - Login/Signup

### LINKED ISSUE #93: [FEATURE] Authentication - Login/Signup
### Description

The project lacks authentication, Authentication would be useful for displaying history, subscriptions etc.

It can be implemented by using bcrypt and JWT token.

### Screenshots

_No response_

### Additional information

Please assign this issue to me.

### PR DESCRIPTION
**Pull request by kartikayasija**
## 🛠️ Fixes Issue: #93 

close #93 

## 👨‍💻 Changes proposed:

Authentication integrated with Firebase

Please assign me this issue before merging the PR.

## 📷 Screenshots

https://github.com/Fenrir-04/Algo-Media/assets/115306535/82402b9d-17f7-4192-9c6b-dfd3fce77a3f

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of GSSOC23

### CODE REVIEW

**Comment by KOMALDEWNANI** [comment]
Hey @kartikayasija, please resolve the merge conflicts.

**Comment by kartikayasija** [comment]
hello @KOMALDEWNANI , I have resolved the conflicts.

**Comment by KOMALDEWNANI** [comment]
Hey @kartikayasija, could you please tell how one has to update the required firebase environment variables? Could you update the readme file to describe this in detail?

**Comment by KOMALDEWNANI** [comment]
You've done a great job 👏🚀

**Comment by kartikayasija** [comment]
Thanks @KOMALDEWNANI , I have updated Readme file.
image

**Pull request merged**
