### PR TITLE
bg changed to #212427 and API_KEY secured at .env

### PR DESCRIPTION
**Pull request by arnab-sur**
1. Changed background colour in layout.jsx from pure black to #212427
2.  Stored api key in .env file and put it in gitignore
3.  Create a .env file in the root folder and store the api key as REACT_APP_RAPID_API_KEY = <KEY> in the file

### CODE REVIEW

**Comment by yashvardhan-verma** [comment]
please create a issue explaining this and link that issue with this PR. and you also need to update **README** to explain that now everyone need to add a **.env** file.

**Comment by arnab-sur** [comment]
ok doing that.

**Comment by Fenrir-04** [comment]
@arnab-sur did you update the README ?

**Comment by Fenrir-04** [comment]
@arnab-sur hey you have couple of conflicts in fetchfromapi.js and Layout.jsx file, Please resolve them asap

**Pull request closed without merging**
