### PR TITLE
Added prettier workflow

### LINKED ISSUE #144: Add the prettier linter workflow
### Description

As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using the prettier linter in GitHub actions. So I would like to add the prettier linter to ensure proper and uniform linting of the codebase. 

I would like to work on this as a part of GSSoC 23.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by metabiswadeep**
## 🛠️ Fixes Issue: ""

Fixes #144 

## 👨‍💻 Changes proposed:

- Added the prettier linter to ensure proper and uniform linting of the codebase.
- For the linter to run successfully please open the settings of the repo go to Actions -> General -> workflow permissions and enable read and write permissions.

Actions - Google Chrome 21-06-2023 21_47_50

## 📷 Screenshots

Actions - Google Chrome 21-06-2023 21_49_42

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of GSSOC23

### CODE REVIEW

**Comment by metabiswadeep** [comment]
@Fenrir-04 Can you please merge this PR if no changes are necessary?

**Comment by metabiswadeep** [comment]
@Fenrir-04

**Comment by Fenrir-04** [comment]
hey @metabiswadeep , there is a linting error while checking

**Comment by metabiswadeep** [comment]
@Fenrir-04 The linter error will be automatically solved once the PR is merged. It happens due to a lack of permissions in the PR which gets solved once the linter starts running on the repo. After merging, the later PRs to the repo will not have any further linting errors.

**Comment by metabiswadeep** [comment]
@Fenrir-04

**Comment by Fenrir-04** [comment]
@metabiswadeep there are conflicts in constants.js file, please resolve them asap

**Comment by metabiswadeep** [comment]
Done @Fenrir-04

**Pull request merged**
