### PR TITLE
Migrate AlgoMedia to YouTube APIs for Enhanced Functionality

### PR DESCRIPTION
**Pull request by kartikayasija**
## 🛠️ Fixes Issue: #89 

I have updated the official youtube API , just generate API Key from google developers console,
.env:
`
     REACT_APP_APIKEY=<APIKEY>
`

## 📷 Screenshots

image

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of GSSOC23

### CODE REVIEW

**Comment by kartikayasija** [comment]
Please review.

**Comment by KOMALDEWNANI** [comment]
Could you please update the README as well? Additionally, I've noticed that in every file, we are creating a loader function and calling a function with different URLs to fetch data from the API. I believe it would be more efficient to create different functions in one file and use them instead to fetch the data from the API. What do you think?

**Comment by kartikayasija** [comment]
@KOMALDEWNANI yes, that approach would be more efficient. I'll do the changes.

**Comment by kartikayasija** [comment]
I have done the changes.

**Comment by KOMALDEWNANI** [comment]
There are merge conflicts in Videos.jsx file and fetchFromAPI.js file. Please resolve them. Also could you please show video of the application after the changes?

**Comment by kartikayasija** [comment]
https://github.com/Fenrir-04/Algo-Media/assets/115306535/b82a4909-ec1c-4c3b-8370-4464a53daf14

**Comment by KOMALDEWNANI** [comment]
Is this still responsive?

**Comment by KOMALDEWNANI** [comment]
Do the suggested changes I gave after reviewing, then I will merge. Thanks!

**Comment by kartikayasija** [comment]
APIs :
image
Readme:
image

**Comment by kartikayasija** [comment]
Thankyou @KOMALDEWNANI, Please add the labels for GSSOC.

**Comment by KOMALDEWNANI** [comment]
Thanks, @kartikayasija for contributing. Keep up the commendable work! 👏

**Pull request merged**
