### PR TITLE
added youtube-like video information display

### PR DESCRIPTION
**Pull request by pratyush-ksingh**
## 👨‍💻 Changes proposed:

Addition of description section which contains clickable links, addition of feature that displays  video title, channel name, like count similar to how YouTube presents these details. 

#### Discord username 
Pratyush Kumar Singh#4811

 

 

## 📷 Screenshots
description added

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of GSSOC23

### CODE REVIEW

**Comment by KOMALDEWNANI** [comment]
If the description is too long then how would you handle?

**Comment by Fenrir-04** [comment]
hey @pratyush-ksingh there is some conflict in VideoDetail.jsx file, Please review it.

**Comment by pratyush-ksingh** [comment]
> If the description is too long then how would you handle?

there is no problem in that, it is already working fine

**Comment by pratyush-ksingh** [comment]
> hey @pratyush-ksingh there is some conflict in VideoDetail.jsx file, Please review it.

ok, I will review it

**Comment by KOMALDEWNANI** [comment]
> > If the description is too long then how would you handle?
> 
> there is no problem in that, it is already working fine

But how? Would it be working like Youtube, i.e., when the description is long it would trim it and show more would be displayed? 

image

**Comment by harmeetsingh11** [comment]
Is anyone working on this issue?

**Pull request closed without merging**
