### PR TITLE
Form design

### LINKED ISSUE #166: [Style Change] Balance dark and light element in login and signup page
### Description

Currently, the color combination of the signup and login page is too dark as shown below.

 All the elements on this page have color properties that are in the dark color category. This reduces the contrast, visibility, and readability of the page. I want to change the color of the form fields and display the form as a card which will balance the dark and light elements of the page. Also, add some other changes which will increase the contrast of both of these pages.

Normally, it is recommended to display light elements on dark background and dark elements on light background, I will use this principle and make the page more visually appealing to users.

### Screenshots

_No response_

### Additional information

_No response_

### Checklist

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
## 🛠️ Fixes Issue:
 Issue  #166 **[Style Change] Balance dark and light element in login and signup page**
closes  #166

## 📷 Final Output

https://github.com/Fenrir-04/Algo-Media/assets/86224794/dfb0130c-1e4b-4759-b488-52aa5ff36d56

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of GSSOC23

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@Fenrir-04 can you please review this PR!!

**Comment by AlfiyaSiddique** [comment]
@Fenrir-04, please review this PR!!

**Comment by AlfiyaSiddique** [comment]
@Fenrir-04 , can you please review this PR before 10 August, cause after that points will not be counted.

**Comment by AlfiyaSiddique** [comment]
Hey @Fenrir-04 , please review this Pr!!

**Comment by AlfiyaSiddique** [comment]
@Fenrir-04  can you please review this PR before 10 August!!

**Comment by AlfiyaSiddique** [comment]
@Fenrir-04, please review this PR!!

Just Mentioning you again and again to remind you.

**Comment by Fenrir-04** [comment]
@AlfiyaSiddique it has some linting error while merging, please solve it asap.

**Comment by AlfiyaSiddique** [comment]
@Fenrir-04 how can I find where the error where it is occurring and how to solve that can you give a description of this?

**Pull request merged**
