### PR TITLE
Error page Added

### PR DESCRIPTION
**Pull request by PatilHarshh**
Error page added with proper routing
@ahegde3 @Fenrir-04

Issue No : #57

### CODE REVIEW

**Comment by PatilHarshh** [comment]
@Fenrir-04

**Comment by Fenrir-04** [comment]
@PatilHarshh you have some conflicts in app.jsx file, please resolve them.

**Comment by PatilHarshh** [comment]
done @Fenrir-04

**Comment by PatilHarshh** [comment]
Can you Check Once @Fenrir-04

**Pull request merged**
