### PR TITLE
show password

### LINKED ISSUE #162: [FEATURE]  Add show password feature
### Description

I want to add a show password and hide the password icon in the password field similar to the functionality shown below: 

## Sample Video

https://github.com/SurajPratap10/Imagine_AI/assets/86224794/c712c99f-0688-4d4c-92bf-b5616817a336

### Additional information

_No response_

### Checklist

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
## 🛠️ Fixes Issue:
 Closes #162

Fixes Issue #162 

## 👨‍💻 Changes proposed:
Use material UI class to implement an eye icon in the password field 
Used states to change the password type on click event.

## 📷 Screenshots (OutputVideo)

https://github.com/Fenrir-04/Algo-Media/assets/86224794/d1a97bab-a534-42ab-8b16-1ccec0190ed0

## Discord Username
Alfiya Siddique#0459

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of GSSOC23

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
Hello @Fenrir-04 
Can you please add **gssoc23** and  **label3** labels on this PR!
These are the labels present in the issue related to this PR.

**Comment by AlfiyaSiddique** [comment]
Hey @Fenrir-04 , please add gssoc labels on this PR!!

**Comment by AlfiyaSiddique** [comment]
Hello @Fenrir-04 

I request you to add gssoc23 labels on this merged PR!!

**Comment by AlfiyaSiddique** [comment]
Hello, @Fenrir-04 ! 👋🏻

Is something wrong with my PRs??
Why aren't you adding gssoc23 labels to my merged PRs?
I request you to add the labels, Please 🙏

**Comment by Fenrir-04** [comment]
sorry for the late reply @AlfiyaSiddique , didn't check the github nowadays due to college end sems.

**Comment by AlfiyaSiddique** [comment]
> sorry for the late reply @AlfiyaSiddique , didn't check the github nowadays due to college end sems.

No problem @Fenrir-04 , completely understand. Just mentioning every day about labels to remind you. 
Really appreciate your hard work in managing the project. 
Keep up the good work🙌🏻👍🏻.

**Comment by Fenrir-04** [comment]
@AlfiyaSiddique yeah thanks, and you too :)

**Pull request merged**
