### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ayush-Tibrewal**
new look
issue #4

### CODE REVIEW

**Review by Fenrir-04 — CHANGES_REQUESTED** [review]
you have wrote a nice README but have used same lines over and over, that makes it look overdone.
Please consider this and make changes accordingly.

**Comment by Ayush-Tibrewal** [comment]
@Fenrir-04 you closed this repo ?

**Comment by Fenrir-04** [comment]
sorry it was a mistake

**Comment by Ayush-Tibrewal** [comment]
@Fenrir-04 now check made the changes

**Pull request merged**
