### PR TITLE
Responsiveness bug

### LINKED ISSUE #109: [FEATURE] Responsiveness improvement.
### Description

It is not responsive in mobile screen. 
It is only responsive till 440px.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kartikayasija**
## 🛠️ Fixes Issue: #109 
close #109 

Now It is responsive till 290px
## 📷 Screenshots

https://github.com/Fenrir-04/Algo-Media/assets/115306535/756e2490-172f-41de-9a9d-6213228cb477

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of GSSOC23

### CODE REVIEW

**Comment by Fenrir-04** [comment]
hey @kartikayasija, it has some conflicts in Videos.jsx file, Please review it.

**Comment by kartikayasija** [comment]
Resolved 👍

**Comment by kartikayasija** [comment]
Could you please raise its level as I have made a significant change?

**Comment by KOMALDEWNANI** [comment]
Considering that these changes pertain to certain user interface adjustments, it would be suitable to categorize this as level 1.

**Comment by kartikayasija** [comment]
Okay, Thanks for merging the PR.

**Pull request merged**
